version: "3"

services:
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
      - "rabbitdata:/var/lib/rabbitmq/"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_VHOST}
  postgres:
    image: "postgres"
    ports:
      - 5432:5432
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "pgdata:/var/lib/postgresql/data/"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_INITDB_ARGS=--encoding=UTF8

volumes:
  rabbitdata:
    name: rabbitdata
  pgdata:
    name: pgdata

networks:
  default:
    name: gall
